version: '3'
# services
services:
  
  # Symfony service to provide api
  php:
    container_name: php
    image: webdevops/php-nginx-dev:7.3
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.php
      - PHP_MAX_EXECUTION_TIME=86400
    ports:
      - 8080:80